<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net481</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="StlToStep\" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="AlibreAddOn">
        <HintPath>..\..\..\..\AlibreLib\AlibreAddOn.dll</HintPath>
      </Reference>
      <Reference Include="AlibreX">
        <HintPath>..\..\..\..\AlibreLib\AlibreX.dll</HintPath>
      </Reference>
      <Reference Include="System.Windows.Forms" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="AlibreImportOpen.cs">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <None Update="AlibreExportOpen.adc">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="3DPrint.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="3DPrint.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="nexus.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="StlToStep\stltostp.exe">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
