; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "AlibreImportStlAsStep"
#define MyAppVersion "1.1"
#define MyAppPublisher "David Bolsover"
#define MyAppURL "https://github.com/bolsover/AlibreImportStlAsStep"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{378829C4-F122-5217-92E0-E36ADD4F9AA8}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\AlibreImportStlAsStep
DefaultGroupName={#MyAppName}
;LicenseFile=D:\Repository\Jetbrains\Bolsover\AlibreExportOpen\Copyright and License.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=D:\02_Repository\02_Bolsover\AlibreImportStlAsStep\AlibreImportStlAsStep\bin\Debug\net481\Setup
OutputBaseFilename=AlibreImportStlAsStep
SetupIconFile=D:\02_Repository\02_Bolsover\AlibreImportStlAsStep\AlibreImportStlAsStep\bin\Debug\net481\nexus.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64os
ArchitecturesInstallIn64BitMode=x64os

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "D:\02_Repository\02_Bolsover\AlibreImportStlAsStep\AlibreImportStlAsStep\bin\Debug\net481\3DPrint.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\02_Repository\02_Bolsover\AlibreImportStlAsStep\AlibreImportStlAsStep\bin\Debug\net481\3DPrint.svg"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\02_Repository\02_Bolsover\AlibreImportStlAsStep\AlibreImportStlAsStep\bin\Debug\net481\AlibreImportStlAsStep.adc"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\02_Repository\02_Bolsover\AlibreImportStlAsStep\AlibreImportStlAsStep\bin\Debug\net481\AlibreImportStlAsStep.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\02_Repository\02_Bolsover\AlibreImportStlAsStep\AlibreImportStlAsStep\bin\Debug\net481\StlToStep\stltostp.exe"; DestDir: "{app}"; Flags: ignoreversion
;Source: "D:\02_Repository\02_Bolsover\AlibreImportStlAsStep\AlibreImportStlAsStep\bin\Debug\net481\AlibreExportOpen.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\02_Repository\02_Bolsover\AlibreImportStlAsStep\AlibreImportStlAsStep\bin\Debug\net481\nexus.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Registry]
Root: HKLM; Subkey: "SOFTWARE\Alibre Design Add-Ons"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Alibre Design Add-Ons"; ValueType: string; ValueName: "{{378829C4-F122-5217-92E0-E36ADD4F9AA8}"; ValueData: "{autopf}\{#MyAppName}"; Check: IsAdminInstallMode