<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net481</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="AlibreAddOn">
        <HintPath>..\..\..\..\AlibreLib\AlibreAddOn.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="AlibreX">
        <HintPath>..\..\..\..\AlibreLib\AlibreX.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="System.Windows.Forms" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="AlibreImportOpen.cs">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <None Update="AlibreImportStlAsStep.adc">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="3DPrint.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="3DPrint.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="nexus.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="test.stl">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="test.bat">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="stltostp.exe">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="concrt140.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="msvcp140.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="msvcp140_1.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="msvcp140_2.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="msvcp140_atomic_wait.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="msvcp140_codecvt_ids.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="vcruntime140.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="vcruntime140_1.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
